# Create a gitignored config/application.yml file with the following values
SENDGRID_PASSWORD:
SENDGRID_USERNAME:

SECRET_KEY_BASE:

AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
development:
  AWS_BUCKET:
production:
  AWS_BUCKET: